### ISSUE TITLE
Error running `go run main.go serve` with go version go1.15.6 darwin/amd64

### ISSUE THREAD

**Issue by cramhead** [jensneuse/graphql-gateway#5]
The README.md suggests running `go run main.go serve` , to start, but when doing so with go 1.15.6 it fails. You may not consider this a bug as the README.md explicitly states to run go 1.13. If so, this issue simply tracks an issue that would be raised when upgrading. 
I have no knowledge of go so please excuse me if this is some totally novice issue. I'll spend some time learning go and see it I can resolve this issue. If I do so would you like a PR?

**Comment by jensneuse** [comment]
I've updated the dependencies. Should work now. Can you confirm?

**Comment by cramhead** [comment]
That fixed the issue. Thx
