### ISSUE TITLE
Unexpected result for person

### ISSUE THREAD

**Issue by cramhead** [jensneuse/graphql-gateway#6]
Now that that gateway is up, I ran some queries and got some unexpected results. I thought you'd want to know. I'll add them individually. 

In this case I was expecting the id to be `"1"`
![image](https://user-images.githubusercontent.com/386035/103303702-83919400-49bb-11eb-8901-aff8c89dff5e.png)

**Comment by jensneuse** [comment]
It would be helpful to see the config/schema too.

**Comment by cramhead** [comment]
I should add a few details here. I get the same issue when I run the docker container or the build the source and run it.
The schema is that associated with the project's by defaults, i.e. I did not specify anything other than the `docker run -p 0.0.0.0:9111:9111 jensneuse/graphql-gateway serve` or `go run main.go serve`. 
I'm not sure these errors are expected
